---
title: "Wellness Technology Case Study - Bellabeat Analysis"
author: "Rachel"
date: "2023-03-10"
output: html_document
---
  
## Scenario
  
# In this scenario, I became a junior data analyst working on the marketing analyst team at Bellabeat, a women-owned high-tect manufacturer and wellness company of health-focused products for women. Bellabeat was founded by Urška Sršen and Sandro Mur in 2014, based in San Francisco. Sršen believes that analyzing smart device fitness data could help on company's development and gaining better future opportunities. 
# In this case study, we are going to explore and analyze a fitness tracker dataset, while gaining insight for Bellabeat.

> ## 1. Ask

### 1.1 Objective/ Business task 
Through analyzing a fitness tracker dataset and help guide marketing strategy, suggestion, and plans for the company.

### 1.2 Stakeholders

#### Primary stakeholders: 

#* Urška Sršen, Bellabeat's cofounder and chief creative officer
#* Sandro Mur, mathemactician and Bellabeat's cofounder
#* Bellabeat marketing analytics team

#### Secondary stakeholders:
#* Bellabeat's users
#* General public

> ## 2. Prepare
  
#The data using in this case study is a public dataset from Kaggle, an online community platform for data science learning. The dataset "FitBit Fitness Tracker Data" contains s personal fitness tracker from thirty fitbit users. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring. It includes information about daily activity, steps, and heart rate that can be used to explore users’ habits.


#There are 18 comma-separated values (csv) files from the dataset. I downloaded all of them and stored them in my laptop drive. Each files are arranged, or ordered by the user Ids, and they both stored in long and wide format. 


#We are going to identify the source of the data by checking the ROCCC.

#### Reliable

#The dataset contains only 33 users, which may not be a good sample of poplulation to represent all user from Fitbit. Also, the users' age, gender, races, and location are all unknown, which causes bias.

#### Original

#The dataset generated by respondents to a distibuted survey via Amazon Mechanical Turk. It made available through Möbius, one of a data scientist from Kaggle user. This consider the dataset is a second-party data, which the data was collected by a group directly from its audience.

#### Comprehensive

#The dataset contains important data such as number of calories burned, steps each day walked etc. However, the age group and gender of the users are missing and this might affect the insight we could gain.

#### Current

#The dataset was collected between 03-12-2016 to 05-12-2016. A dataset collected 6 years ago is considered out of date. Moreover, the time period collected from the dataset had only three months, this might not be a ideal time length for a good dataset.

#### Cited

#Unknown. The dataset did not have any citation.

> ## 3. Process

#I have choosen to use programming R for my first case study project. In the coming Process stage, we are going to use R to preview, sort, filter, and clean the data. 

### 3.1 Install and load packages
#First of all, we will install and load the packages that we need for the project.
```{r}
install.packages("tidyverse")
install.packages("lubridate")
install.packages("skimr")
install.packages("janitor")
install.packages("Tmisc")
install.packages("here")
```

```{r}
library(tidyverse)
library(lubridate)
library(skimr)
library(janitor)
library(Tmisc)
library(here)
```

### 3.2 Import data and view data
#Then, we will import the data files and have a look on them.
```{r}
daily_act <- read_csv("dailyActivity_merged.csv")   
daily_calories <- read_csv("dailyCalories_merged.csv")  
daily_steps <- read_csv("dailySteps_merged.csv")
```
#We have read and saved the csv files and named them "daily_act", "daily_calories", and "daily_steps".

#Then, we can use *head()* to preview the datasets.
```{r}
head(daily_act)
head(daily_calories)
head(daily_steps)
```


### 3.3 Clean the datasets
#The dataset mentioned it contain 30 people of sample size based on their ID number (Id). We will need to check how many unique users (Id) in each dataset.
```{r}
n_unique(daily_act$Id)
n_unique(daily_calories$Id)
n_unique(daily_steps$Id)
```
#There are 33 users in each dataset in total.

#Next, we need to check any duplicates by counting the sum of duplicates.
```{r}
sum(duplicated(daily_act))
sum(duplicated(daily_calories))
sum(duplicated(daily_steps))
```
#Great. The code returns 0 that's mean there are no duplicates

#After that, let's remove any N/As using *distinct()* and *drop_na()* function in the dataset.
```{r}
daily_act <- daily_act %>% 
  distinct() %>% 
  drop_na()
daily_calories <- daily_calories %>% 
  distinct() %>% 
  drop_na()
daily_steps <- daily_steps %>% 
  distinct() %>% 
  drop_na()
```

#Double check any missing value using *is.na()* function
```{r}
sum(is.na(daily_act))
```

#Let's check the data type by using *str()* function.
```{r}
str(daily_act)
str(daily_calories)
str(daily_steps)
```


#We can see that the data from column ActivityDate are formatted in *chr (character)*. Since because it is a date, it should be stored as *Date* type. To change the data type format, we will use the *mutate()* function.
```{r}
daily_act <- daily_act %>% 
  rename(Date = ActivityDate) %>%  # rename column name
  mutate(Date = as_date(Date, format = "%m/%d/%Y"))

daily_calories <- daily_calories %>%
  rename(Date = ActivityDay) %>% 
  mutate(Date = as_date(Date, format = "%m/%d/%Y")) # change data type format

daily_steps <- daily_steps %>% 
  rename(Date = ActivityDay) %>% 
  mutate(Date = as_date(Date, format = "%m/%d/%Y"))
```


#Check the data type again, we can use *glimpse()* this time.
```{r}
glimpse(daily_act)
glimpse(daily_calories)
glimpse(daily_steps)
```

#The data type of ActivityDate has been changed to *date* and renamed as "Date" successfully.


#We would also like to add a new column showing the day of the week, to help for analyzing later on.
```{r}
daily_act <- daily_act %>% 
  mutate(Day = weekdays(daily_act$Date))
daily_calories <- daily_calories %>% 
  mutate(Day = weekdays(daily_calories$Date))
daily_steps <- daily_steps %>% 
  mutate(Day = weekdays(daily_steps$Date)) # Add a new column named 'Day' using the weekdays()
```


#Let's have a look at the new column, we now have a new column 'Day' showing which day is it.
```{r}
head(daily_calories)
```

> ## 4. Analyze
#In the Analyze stage, we will start putting it to work. 

#First, let's find the mean, max, min.
```{r}
daily_act %>%
  group_by(Id) %>% 
  summarize(mean_steps = mean(TotalSteps),   
            max_steps = max(TotalSteps),
            min_steps = min(TotalSteps))
```

```{r}
daily_act %>% 
  select(TotalSteps) %>% 
  summary()
```
#The results showing that the mean daily steps of these 33 user is 7638, while maximum is 36019 and minimum is 0. 

#We would like to distinguish the intention of the user by grouping them into 4 categorizes by using the *mutute()* function to create a new column. I will set 7500 here as the median number for the steps.
```{r}
daily_act02 <- daily_act %>% 
  mutate(UserType = case_when(
    TotalSteps < 4000 ~ "Sedentary Active",
    TotalSteps >= 4000 & TotalSteps < 7500 ~ "Lightly Active",
    TotalSteps >= 7501 & TotalSteps < 10000 ~ "Moderately Active",
    TotalSteps >= 10001 ~ "Very Active"
  ))
as_tibble(daily_act02)
```

```{r}
daily_act02 %>% 
  select(Id, Date, TotalSteps, Calories, Day, UserType)
```

> ## 5. Share
  
#Let's create some visual graph to have a look.
```{r}
install.packages("ggplot2") # install and load package 
library(ggplot2)

daily_act02$Day <- factor(daily_act02$Day, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

ggplot(data = daily_act02)+
  geom_bar(mapping = aes(x=Day, fill=UserType))
```

#### Some findings

#* The bar chart above showing that Tuesday and Wednesday have the most user are being active, while Monday and Sunday have less user being active
#* Wednesday and Saturday have the most user who are consider "lightly active" compared to the rest of the days



#Now, let's going through the relationship between total steps and calories, we will use *geom_smooth()* function to graph for the two variables.
```{r}
ggplot(data = daily_act02)+
  geom_smooth(mapping = aes(x=Calories, y=TotalSteps)) + ylab('Total Steps')
```
#### Some findings

#* The trend went very smooth, showing a positive relationship between total steps walked each day and calories burned each day. The more steps user walked, the more calories they can burn


> ## 6. Act
  
  ### Conclusion
#Summed up the factors that we outlined above, we can draw the conclusion that users have preference on week of day to be active or less active.

### Recommendation
#1. Bellabeat app notification
#All user from Bellabeat are linked and being tracked to their smart device. Mobile app development team may consider sending notification when user are being not that active enough on the Day they usually being lazy.

#2. Health information 
#Everyone know regularly exercising are benefits to their body. People from now a days are being busy from their work and school. The mobile app could send user reminder if they didn't walk sufficient amount of steps or not being active for a time period.
